{% set name = "lbcommon" %}
{% set version = "0.0.11" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/LbCommon-{{ version }}.tar.gz
  sha256: 5f03c7f41f147ab9cbe0c3567731a606af958aef489be87d4100d96a09ee25e6

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 1

requirements:
  host:
    - python {{ python_min }}
    - setuptools >=61.2
    - nose >=1.0
    - setuptools-scm
    - pip
  run:
    - python >={{ python_min }}

test:
  imports:
    - LbCommon
    - LbCommon.CMake
    - LbCommon.ConfigFile
    - LbCommon.Env
    - LbCommon.Log
    - LbCommon.Option
    - LbCommon.Processes
    - LbCommon.Script
    - LbCommon.Temporary
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://gitlab.cern.ch/lhcb-core/LbCommon
  summary: LHCb Common tools
  license: GPL-3.0-or-later
  license_file: LICENSE

extra:
  recipe-maintainers:
    - bcouturi
    - chrisburr
